SCHEMES_DATABASE = [
  {
    "id": 1,
    "scheme_name": "Pradhan Mantri Virasat Ka Samvardhan (PM VIKAS)",
    "ministry_or_department": "Ministry of Minority Affairs",
    "eligibility_category": "Notified Minority Communities (Muslims, Christians, Sikhs, Buddhists, Parsis, Jains)",
    "min_age": 18,
    "max_age": 45,
    "max_income": "Family income criteria as per EWS/Minority guidelines",
    "business_sector": "Artisan, Handloom, Handicraft, and Skill-based Micro Enterprises",
    "target_group": "Minority artisans, women, and youth dropouts",
    "main_benefit": "Integrated skill training, leadership development, open schooling, and credit/market linkage",
    "min_loan": "N/A (Grant/Training Scheme with stipend)",
    "max_loan": "N/A (Direct micro-credit linkage through partner institutions)",
    "subsidy": "100% training & stipend subsidy + ₹4,000 post-placement support",
    "description": "Converges 5 erstwhile schemes (Seekho Aur Kamao, Nai Manzil, Nai Roshni, USTTAD, Hamari Dharohar) to preserve artisan heritage and provide skilling.",
    "financial_assistance_details": "Free NSQF-aligned training, daily training allowance/stipend, hostel accommodation, and certification.",
    "documents_required": ["Aadhaar Card", "Minority Self-Declaration/Certificate", "Educational Proof", "Bank Passbook", "Passport Photo"],
    "application_process": "Online application via Skill India Digital Hub (SIDH) or official PM VIKAS portal.",
    "nature_of_loan": "Non-loan / Direct Benefit Transfer & Skill Grant",
    "interest_rate": "0%",
    "official_website_link": "https://pmvikas.minorityaffairs.gov.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://pmvikas.minorityaffairs.gov.in/candidate-login"
  },
  {
    "id": 2,
    "scheme_name": "New Swarnima Scheme for Women - NBCFDC",
    "ministry_or_department": "Ministry of Social Justice and Empowerment / NBCFDC",
    "eligibility_category": "Women belonging to Other Backward Classes (OBCs)",
    "min_age": 18,
    "max_age": 55,
    "max_income": "₹3,00,000 per annum (Rural & Urban)",
    "business_sector": "Small Scale Businesses, Agro-processing, Service Units, Trading",
    "target_group": "Targeted towards OBC women entrepreneurs",
    "main_benefit": "Concessional term loan up to ₹2,00,000 for financial self-reliance",
    "min_loan": "₹10,000",
    "max_loan": "₹2,00,000",
    "subsidy": "Financing up to 95% of project cost with low interest subvention",
    "description": "Provides concessional credit to targeted OBC women entrepreneurs to start income-generating micro-enterprises.",
    "financial_assistance_details": "Loan up to ₹2 Lakh with beneficiary contribution of only 5%. Term loan tenure up to 8 years.",
    "documents_required": ["Aadhaar Card", "OBC Caste Certificate", "Income Certificate", "Business Project Plan", "Bank Passbook"],
    "application_process": "Apply offline/online through State Channelizing Agencies (SCAs), RRBs, or nationalized banks associated with NBCFDC.",
    "nature_of_loan": "Term Loan",
    "interest_rate": "5% p.a.",
    "official_website_link": "https://nbcfdc.gov.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://nbcfdc.gov.in/schemes/new-swarnima-scheme"
  },
  {
    "id": 3,
    "scheme_name": "Saksham Scheme - NBCFDC",
    "ministry_or_department": "Ministry of Social Justice and Empowerment / NBCFDC",
    "eligibility_category": "Young OBC Professionals & Technocrats",
    "min_age": 18,
    "max_age": 35,
    "max_income": "₹3,00,000 per annum",
    "business_sector": "Professional Services (Clinics, Law Offices, IT Units, Engineering Consultancy)",
    "target_group": "Young professional qualification degree/diploma holders from Backward Classes",
    "main_benefit": "Term loan up to ₹10 Lakh for professional enterprise establishment",
    "min_loan": "₹50,000",
    "max_loan": "₹10,00,000",
    "subsidy": "85% - 90% loan coverage of project cost at subsidized interest rates",
    "description": "Financial assistance to young OBC professionals to set up self-employment ventures in their specialized domains.",
    "financial_assistance_details": "Loans up to ₹10 Lakh at 6% to 8% interest per annum with up to 10 years repayment period.",
    "documents_required": ["Aadhaar Card", "OBC Certificate", "Professional Degree/Diploma Certificate", "Business Plan", "Income Proof"],
    "application_process": "Submit application through State Channelizing Agencies (SCAs) or Jan Samarth Portal.",
    "nature_of_loan": "Term Loan",
    "interest_rate": "6% to 8% p.a.",
    "official_website_link": "https://nbcfdc.gov.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://www.jansamarth.in"
  },
  {
    "id": 4,
    "scheme_name": "Shilp Sampada - NBCFDC",
    "ministry_or_department": "Ministry of Social Justice and Empowerment / NBCFDC",
    "eligibility_category": "OBC Artisans and Traditional Craft Workers",
    "min_age": 18,
    "max_age": 60,
    "max_income": "₹3,00,000 per annum",
    "business_sector": "Handicrafts, Handlooms, Pottery, Metal Craft, Woodwork",
    "target_group": "Artisans and craftspersons from Backward Classes",
    "main_benefit": "Skill upgrading, machinery acquisition, and working capital term loans",
    "min_loan": "₹25,000",
    "max_loan": "₹10,00,000",
    "subsidy": "Concessional credit coverage up to 85% of total project cost",
    "description": "Financial support for upgrading traditional tools, buying modern craft equipment, and expanding craft businesses.",
    "financial_assistance_details": "Term loan up to ₹10 Lakh per beneficiary at 6% p.a. interest rate for up to 10 years.",
    "documents_required": ["Aadhaar Card", "Artisan ID/Pehchan Card", "OBC Certificate", "Bank Passbook", "Income Proof"],
    "application_process": "Apply through State Channelizing Agencies (SCAs) or designated partner banks.",
    "nature_of_loan": "Term Loan & Working Capital",
    "interest_rate": "6% p.a.",
    "official_website_link": "https://nbcfdc.gov.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://nbcfdc.gov.in"
  },
  {
    "id": 5,
    "scheme_name": "Credit Enhancement Guarantee Scheme for Scheduled Castes (CEGSSC)",
    "ministry_or_department": "Ministry of Social Justice and Empowerment / IFCI",
    "eligibility_category": "Scheduled Caste (SC) Entrepreneurs (Individuals or >51% SC Owned Companies)",
    "min_age": 18,
    "max_age": "No Upper Limit",
    "max_income": "No Ceiling",
    "business_sector": "Manufacturing, Trading, and Services",
    "target_group": "SC-owned MSMEs and commercial businesses",
    "main_benefit": "Credit guarantee cover for collateral-free bank loans",
    "min_loan": "₹15,00,000",
    "max_loan": "₹5,00,00,000",
    "subsidy": "60% to 100% guarantee cover provided to lending banks/financial institutions",
    "description": "Encourages banks to extend credit to SC entrepreneurs by providing government credit guarantee cover.",
    "financial_assistance_details": "100% guarantee for loans up to ₹1 Cr, 80% for ₹1–₹2 Cr, and 70% for ₹2–₹5 Cr.",
    "documents_required": ["SC Caste Certificate", "Company Registration/GSTIN", "Project Report", "Aadhaar & PAN", "Bank Statements"],
    "application_process": "Apply directly through participating Public/Private Sector Banks registered with IFCI CEGSSC.",
    "nature_of_loan": "Credit Guarantee Facility for Term Loans / Working Capital",
    "interest_rate": "As per bank's commercial loan rates",
    "official_website_link": "https://ifcicegssc.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://ifcicegssc.in"
  },
  {
    "id": 6,
    "scheme_name": "Divyangjan Swavalamban Yojana - NDFDC",
    "ministry_or_department": "Ministry of Social Justice and Empowerment / NDFDC",
    "eligibility_category": "Persons with Disabilities (PwDs / Divyangjan) with 40%+ Disability",
    "min_age": 18,
    "max_age": 65,
    "max_income": "No Income Bar",
    "business_sector": "Agriculture, Trade, Manufacturing, Services, and Higher Education",
    "target_group": "Divyangjan entrepreneurs and self-employed individuals",
    "main_benefit": "Concessional loans for establishing or expanding income-generating ventures",
    "min_loan": "₹50,000",
    "max_loan": "₹50,00,000",
    "subsidy": "Interest rebate of 1% p.a. for women PwDs and regular repayment promptness",
    "description": "Offers soft loans to PwDs to setup commercial ventures and gain economic self-reliance.",
    "financial_assistance_details": "Loan up to ₹50 Lakh at interest rates from 5% to 9% p.a. Repayment up to 10 years.",
    "documents_required": ["Disability Certificate (40%+)", "Aadhaar Card", "Address Proof", "Business Proposal", "Bank Details"],
    "application_process": "Apply online via NDFDC loan account portal or through State Channelizing Agencies / RRBs.",
    "nature_of_loan": "Term Loan",
    "interest_rate": "5% to 9% p.a.",
    "official_website_link": "http://www.ndfdcloanaccount.co.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "http://www.ndfdcloanaccount.co.in"
  },
  {
    "id": 7,
    "scheme_name": "Vishesh Microfinance Yojana - NDFDC",
    "ministry_or_department": "Ministry of Social Justice and Empowerment / NDFDC",
    "eligibility_category": "Persons with Disabilities (PwDs) & Disability SHGs",
    "min_age": 18,
    "max_age": 65,
    "max_income": "No Income Bar",
    "business_sector": "Micro-enterprises, Cottage Industries, Petty Shopkeeping",
    "target_group": "Divyangjan micro-entrepreneurs and SHGs",
    "main_benefit": "Quick microfinance credit for small working capital and quick business needs",
    "min_loan": "₹10,00,000 (per SHG)",
    "max_loan": "₹60,00,000 (per SHG) / ₹60,000 per member",
    "subsidy": "Low-interest micro-credit lines to MFIs/NGOs for rapid disbursement",
    "description": "Microfinance facility designed for fast, collateral-free credit to small PwD-run micro-units.",
    "financial_assistance_details": "Loans up to ₹60,000 per individual at 5% p.a. interest rate for up to 3 years.",
    "documents_required": ["Disability Certificate", "Aadhaar Card", "Bank Account Details", "SHG Registration Proof (if applicable)"],
    "application_process": "Apply through NDFDC microfinance partner NGOs/SCAs or online portal.",
    "nature_of_loan": "Microfinance Working Capital",
    "interest_rate": "5% p.a.",
    "official_website_link": "http://www.ndfdcloanaccount.co.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "http://www.ndfdcloanaccount.co.in"
  },
  {
    "id": 8,
    "scheme_name": "National Bamboo Mission (NBM)",
    "ministry_or_department": "Department of Agriculture and Farmers Welfare",
    "eligibility_category": "Farmers, Bamboo Artisans, FPOs, Agri-entrepreneurs, Private Companies",
    "min_age": 18,
    "max_age": "No Upper Limit",
    "max_income": "No Ceiling",
    "business_sector": "Bamboo Cultivation, Nursery, Primary Processing, Craft & Product Manufacturing",
    "target_group": "Farmers and bamboo sector micro-entrepreneurs",
    "main_benefit": "Direct capital and plantation subsidy for bamboo crop production and manufacturing units",
    "min_loan": "N/A (Capital Subsidy Scheme)",
    "max_loan": "Up to ₹50 Lakh credit linked project support",
    "subsidy": "50% - 60% plantation subsidy; 25% - 50% capital grant for processing machinery",
    "description": "Promotes the growth of the bamboo sector through nursery establishment, plantation, and value-addition units.",
    "financial_assistance_details": "Plantation subsidy up to ₹1,20,000/ha; processing plant grant up to 50% of cost.",
    "documents_required": ["Land Ownership Document/Lease Agreement", "Aadhaar Card", "Project Costing Report", "Bank Account Details"],
    "application_process": "Submit application through State Bamboo Mission (SBM) portals or Ministry portal.",
    "nature_of_loan": "Capital Subsidy / Credit-Linked Back-ended Subsidy",
    "interest_rate": "Standard bank loan interest (subsidy credited to loan account)",
    "official_website_link": "https://nbm.nic.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://nbm.nic.in"
  },
  {
    "id": 9,
    "scheme_name": "Pradhan Mantri Matsya Sampada Yojana (PMMSY)",
    "ministry_or_department": "Department of Fisheries, Ministry of Fisheries, Animal Husbandry and Dairying",
    "eligibility_category": "Fish Farmers, Fishers, SHGs, JLGs, Fisheries Cooperatives, Agri-entrepreneurs",
    "min_age": 18,
    "max_age": "No Upper Limit",
    "max_income": "No Ceiling",
    "business_sector": "Aquaculture, Marine & Inland Fisheries, Fish Processing, Cold Chain, Hatcheries",
    "target_group": "Fishermen, women fish-workers, and fisheries entrepreneurs",
    "main_benefit": "Subsidies up to 60% for establishing fish farms, hatcheries, and cold storage units",
    "min_loan": "₹1,00,000",
    "max_loan": "Up to ₹5 Crore (depending on project size)",
    "subsidy": "40% for General Category; 60% for Women, SC, and ST beneficiaries",
    "description": "Flagship scheme for holistic development of the fisheries sector and boosting fish production.",
    "financial_assistance_details": "Capital grant cover of 40%–60% on total project cost, directly transferred upon project milestones.",
    "documents_required": ["Aadhaar Card", "Land/Pond Details", "Detailed Project Report (DPR)", "Caste Certificate (if applicable)", "Bank Passbook"],
    "application_process": "Apply online via PMMSY MIS portal or through State Fisheries Department offices.",
    "nature_of_loan": "Credit-Linked Back-ended Capital Subsidy",
    "interest_rate": "As applicable by bank",
    "official_website_link": "https://pmmsymis.dof.gov.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://pmmsymis.dof.gov.in"
  },
  {
    "id": 10,
    "scheme_name": "Animal Husbandry Infrastructure Development Fund (AHIDF)",
    "ministry_or_department": "Department of Animal Husbandry and Dairying",
    "eligibility_category": "MSMEs, FPOs, Section 8 Companies, Private Entrepreneurs, Cooperatives",
    "min_age": 18,
    "max_age": "No Upper Limit",
    "max_income": "No Ceiling",
    "business_sector": "Dairy Processing, Meat Processing, Animal Feed Plants, Breed Improvement Facilities",
    "target_group": "Livestock sector investors and agri-processing entrepreneurs",
    "main_benefit": "3% Interest Subvention + up to 25% Credit Guarantee Cover",
    "min_loan": "₹50,00,000",
    "max_loan": "Up to 90% of total project cost",
    "subsidy": "3% p.a. interest subvention for 10 years with 2-year principal moratorium",
    "description": "Incentivizes private investment in livestock processing and animal feed infrastructure.",
    "financial_assistance_details": "Loans up to 90% project cost from scheduled banks; 3% interest discount; credit guarantee via NABARD/CGTMSE.",
    "documents_required": ["DPR / Feasibility Report", "GSTIN & Firm Registration", "Land Documents", "Aadhaar & PAN", "3 Years Audited Statements"],
    "application_process": "Apply online via SIDBI Udyami Mitra portal for AHIDF.",
    "nature_of_loan": "Term Loan",
    "interest_rate": "Commercial bank rate minus 3% subvention",
    "official_website_link": "https://ahidf.udyamimitra.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://ahidf.udyamimitra.in"
  },
  {
    "id": 11,
    "scheme_name": "PM Street Vendor's AtmaNirbhar Nidhi (PM SVANidhi)",
    "ministry_or_department": "Ministry of Housing and Urban Affairs",
    "eligibility_category": "Urban & Peri-urban Street Vendors holding Vending Certificates/Letters of Recommendation",
    "min_age": 18,
    "max_age": "No Upper Limit",
    "max_income": "No Income Bar",
    "business_sector": "Street Vending, Petty Trading, Hawking",
    "target_group": "Street vendors and micro-traders",
    "main_benefit": "Collateral-free working capital loan in progressive tranches with interest subsidy",
    "min_loan": "₹10,00,000 (Tranche 1: ₹10,000)",
    "max_loan": "₹50,000 (Tranche 3)",
    "subsidy": "7% p.a. interest subsidy + up to ₹1,200/year cashbacks on digital payments",
    "description": "Provides micro-credit support to street vendors impacted by disruptions, helping build credit profile.",
    "financial_assistance_details": "Tranche 1: ₹10,000; Tranche 2: ₹20,000; Tranche 3: ₹50,000 upon timely repayment.",
    "documents_required": ["Aadhaar Card", "Certificate of Vending / LOR from Urban Local Body", "Mobile Number linked with Aadhaar", "Bank Account Details"],
    "application_process": "Apply online via PM SVANidhi portal or CSC centers or Jan Samarth.",
    "nature_of_loan": "Working Capital Loan (Collateral Free)",
    "interest_rate": "Market lending rate (effective reduced by 7% subvention)",
    "official_website_link": "https://pmsvanidhi.mohua.gov.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://pmsvanidhi.mohua.gov.in"
  },
  {
    "id": 12,
    "scheme_name": "Prime Minister’s Employment Generation Programme (PMEGP)",
    "ministry_or_department": "Ministry of Micro, Small and Medium Enterprises / KVIC",
    "eligibility_category": "Individual Entrepreneurs, SHGs, Cooperatives, Trusts",
    "min_age": 18,
    "max_age": "No Upper Limit",
    "max_income": "No Income Ceiling",
    "business_sector": "Manufacturing Units and Service/Trading Enterprises",
    "target_group": "Unemployed youth and prospective entrepreneurs",
    "main_benefit": "Credit-linked capital subsidy up to 35% for setting up new micro-units",
    "min_loan": "₹2,00,000",
    "max_loan": "₹50,00,000 (Manufacturing) / ₹20,00,000 (Services)",
    "subsidy": "15% - 35% margin money subsidy depending on category (General/Special) and area (Rural/Urban)",
    "description": "Flagship credit-linked subsidy scheme generating self-employment through micro-enterprise creation.",
    "financial_assistance_details": "Beneficiary contributes 5% to 10% cost; government provides 15% to 35% margin money subsidy; balance is bank loan.",
    "documents_required": ["Aadhaar Card", "EDP Training Certificate", "Project Report", "Class 8th Pass Certificate (for loans > ₹10L Manufacturing / ₹5L Services)", "Caste/Special Category Certificate"],
    "application_process": "Apply online through the KVIC PMEGP e-Portal.",
    "nature_of_loan": "Composite Loan (Term Loan + Working Capital)",
    "interest_rate": "Standard bank lending interest rate",
    "official_website_link": "https://www.kviconline.gov.in/pmegpeportal",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://www.kviconline.gov.in/pmegpeportal"
  },
  {
    "id": 13,
    "scheme_name": "Pradhan Mantri Mudra Yojana (PMMY)",
    "ministry_or_department": "Department of Financial Services, Ministry of Finance",
    "eligibility_category": "Non-Corporate, Non-Farm Small/Micro Enterprises",
    "min_age": 18,
    "max_age": 65,
    "max_income": "No Income Bar",
    "business_sector": "Manufacturing, Trading, Service Sector, Agri-Allied Activities",
    "target_group": "Small shopkeepers, repair shops, artisans, micro-manufacturers",
    "main_benefit": "Collateral-free business loans up to ₹20 Lakh in 3 categories",
    "min_loan": "₹10,000",
    "max_loan": "₹20,00,000 (Tarun Plus category)",
    "subsidy": "No direct subsidy; 2% interest subvention for prompt repayment under Shishu loan category during relief phases",
    "description": "Provides micro-funding to small commercial enterprises across Shishu, Kishore, and Tarun categories.",
    "financial_assistance_details": "Shishu: up to ₹50,000; Kishore: ₹50,001 to ₹5 Lakh; Tarun: ₹5 Lakh to ₹20 Lakh.",
    "documents_required": ["Aadhaar Card", "PAN Card", "Business Proof / Registration", "6-Month Bank Statement", "Quotation for Machinery/Stock"],
    "application_process": "Apply via Jan Samarth Portal, bank branches, or MUDRA portal online.",
    "nature_of_loan": "Term Loan / Working Capital (Mudra Card)",
    "interest_rate": "Base rate linked (usually 8.5% to 12% p.a.)",
    "official_website_link": "https://www.mudra.org.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://www.jansamarth.in"
  },
  {
    "id": 14,
    "scheme_name": "Stand-Up India Scheme",
    "ministry_or_department": "Department of Financial Services, Ministry of Finance / SIDBI",
    "eligibility_category": "SC, ST, and/or Women Entrepreneurs (aged 18+)",
    "min_age": 18,
    "max_age": "No Upper Limit",
    "max_income": "No Ceiling",
    "business_sector": "Manufacturing, Services, Trading, or Agri-Allied Sector (Greenfield Projects)",
    "target_group": "SC, ST, and Women entrepreneurs",
    "main_benefit": "Bank loans between ₹10 Lakh and ₹1 Crore for setting up new greenfield enterprises",
    "min_loan": "₹10,00,000",
    "max_loan": "₹1,00,00,000",
    "subsidy": "Can be converged with state/central capital subsidy programs; lower margin money requirement (15%)",
    "description": "Promotes entrepreneurship at the grassroots level among SC, ST, and Women by facilitating bank credit.",
    "financial_assistance_details": "Composite loan covering up to 85% of project cost; repayment tenure of 7 years with up to 18 months moratorium.",
    "documents_required": ["Aadhaar & PAN", "SC/ST Certificate (if applicable)", "Project Report", "Company Incorporation Certificate / GST", "Bank Account Details"],
    "application_process": "Apply online via Stand-Up Mitra portal or through bank branches.",
    "nature_of_loan": "Composite Loan (Term Loan & Working Capital)",
    "interest_rate": "Lowest applicable rate of the bank for that category (MCLR + Tenor Premium)",
    "official_website_link": "https://www.standupmitra.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://www.standupmitra.in"
  },
  {
    "id": 15,
    "scheme_name": "Credit Guarantee Fund Trust for Micro and Small Enterprises (CGTMSE)",
    "ministry_or_department": "Ministry of Micro, Small and Medium Enterprises / SIDBI",
    "eligibility_category": "New and Existing Micro and Small Enterprises (MSEs)",
    "min_age": 18,
    "max_age": "No Upper Limit",
    "max_income": "No Ceiling",
    "business_sector": "Manufacturing and Service Sectors",
    "target_group": "Micro and Small Enterprise owners seeking collateral-free credit",
    "main_benefit": "Government credit guarantee to banks up to ₹5 Crore loan without third-party collateral",
    "min_loan": "₹1,00,000",
    "max_loan": "₹5,00,00,000",
    "subsidy": "Concessional guarantee fee for women, SC/ST, Divyangjan, and ZED-certified units",
    "description": "Replaces collateral requirements for bank loans to small businesses by offering government credit guarantee.",
    "financial_assistance_details": "75% to 85% guarantee coverage extended to lending institutions for collateral-free MSME loans.",
    "documents_required": ["Udyam Registration Certificate", "Detailed Project Report", "PAN & Aadhaar", "GST Certificate", "Income Tax Returns"],
    "application_process": "Request credit guarantee through CGTMSE Member Lending Institutions (MLIs) / banks during loan sanction.",
    "nature_of_loan": "Term Loan / Credit Facility Guarantee",
    "interest_rate": "As charged by lending institution (capped under CGTMSE norms)",
    "official_website_link": "https://www.cgtmse.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://www.cgtmse.in"
  },
  {
    "id": 16,
    "scheme_name": "PM Vishwakarma Scheme",
    "ministry_or_department": "Ministry of Micro, Small and Medium Enterprises",
    "eligibility_category": "Traditional Artisans and Craftsmen in 18 Trades (e.g. Carpenter, Potter, Blacksmith, Cobbler)",
    "min_age": 18,
    "max_age": "No Upper Limit",
    "max_income": "Family should follow traditional trade rules; one member per family eligible",
    "business_sector": "Traditional Craftsmanship and Artisan Trades",
    "target_group": "Traditional artisans and craftsmen",
    "main_benefit": "ID card, ₹15,000 toolkit voucher, skill training, ₹500/day stipend, and collateral-free loan",
    "min_loan": "₹1,00,00,000 (Tranche 1: ₹1 Lakh)",
    "max_loan": "₹3,00,000 (Tranche 1: ₹1L + Tranche 2: ₹2L)",
    "subsidy": "₹15,00,00 toolkit e-voucher + 8% interest subvention paid by government",
    "description": "Comprehensive support scheme providing recognition, skill enhancement, toolkit incentives, and low-interest credit to artisans.",
    "financial_assistance_details": "Collateral-free loan up to ₹3 Lakh at 5% effective interest rate; ₹15,000 toolkit voucher; ₹500/day skill stipend.",
    "documents_required": ["Aadhaar Card", "Aadhaar-linked Mobile Number", "Bank Account Details", "Ration Card"],
    "application_process": "Register via Common Service Centres (CSC) on the official PM Vishwakarma portal.",
    "nature_of_loan": "Collateral-free Enterprise Loan",
    "interest_rate": "5% p.a. (MoMSME pays balance subvention up to 8%)",
    "official_website_link": "https://pmvishwakarma.gov.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://pmvishwakarma.gov.in"
  },
  {
    "id": 17,
    "scheme_name": "Venture Capital Fund for Scheduled Castes (VCF-SC)",
    "ministry_or_department": "Ministry of Social Justice and Empowerment / IFCI",
    "eligibility_category": "SC Entrepreneurs with enterprises having at least 51% SC stake for 6+ months",
    "min_age": 18,
    "max_age": "No Upper Limit",
    "max_income": "No Ceiling",
    "business_sector": "High-growth Commercial, Industrial, and Technology Enterprises",
    "target_group": "SC-led commercial startups and business units",
    "main_benefit": "Equity financing and debt capital for innovative SC enterprises",
    "min_loan": "₹20,00,000",
    "max_loan": "₹15,00,00,000",
    "subsidy": "Concessional equity/debt capital with long exit horizon",
    "description": "Provides risk capital and equity support to foster entrepreneurship among Scheduled Castes.",
    "financial_assistance_details": "Financing up to 75% of project cost with investment limits ranging from ₹20 Lakh up to ₹15 Crore.",
    "documents_required": ["Caste Certificate of Promoter(s)", "Company Incorporation Docs", "Audited Financials", "Detailed Business Plan", "KYC Documents"],
    "application_process": "Apply directly online via VCF-SC application portal managed by IFCI Venture.",
    "nature_of_loan": "Equity / Convertible Debentures / Debt Capital",
    "interest_rate": "4% to 8% p.a. (depending on structure)",
    "official_website_link": "https://vcfsc.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://vcfsc.in"
  },
  {
    "id": 18,
    "scheme_name": "Venture Capital Fund for Backward Classes (VCF-BC)",
    "ministry_or_department": "Ministry of Social Justice and Empowerment / IFCI",
    "eligibility_category": "OBC Entrepreneurs holding >51% shareholding in the enterprise",
    "min_age": 18,
    "max_age": "No Upper Limit",
    "max_income": "No Ceiling",
    "business_sector": "Manufacturing, IT, Clean Energy, Healthcare, Services",
    "target_group": "Backward class entrepreneurs building commercial businesses",
    "main_benefit": "Concessional debt/equity venture capital for enterprise expansion",
    "min_loan": "₹20,00,000",
    "max_loan": "₹5,00,00,000",
    "subsidy": "Subsidized risk capital funding at lower interest rates",
    "description": "Promotes entrepreneurship among Backward Classes by providing long-term venture support.",
    "financial_assistance_details": "Investment support up to ₹5 Crore per project; loan/equity tenure up to 8 years.",
    "documents_required": ["OBC Certificate of Promoters", "Company Registration Documents", "Project Feasibility Report", "Aadhaar & PAN"],
    "application_process": "Submit application online on the VCF-BC official web portal.",
    "nature_of_loan": "Venture Capital / Debt / Equity",
    "interest_rate": "4% to 8% p.a.",
    "official_website_link": "https://vcfbc.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://vcfbc.in"
  },
  {
    "id": 19,
    "scheme_name": "Credit Guarantee Fund for Micro Units (CGFMU)",
    "ministry_or_department": "Department of Financial Services, Ministry of Finance / NCGTC",
    "eligibility_category": "Micro Enterprises eligible under PMMY and PM SVANidhi",
    "min_age": 18,
    "max_age": 65,
    "max_income": "No Ceiling",
    "business_sector": "Retail, Small Manufacturing, Service Units, Micro-businesses",
    "target_group": "Micro entrepreneurs borrowing through Mudra and SVANidhi",
    "main_benefit": "Portfolio guarantee cover for lending institutions to ensure easy micro-loan availability",
    "min_loan": "₹10,000",
    "max_loan": "₹20,00,000",
    "subsidy": "100% credit guarantee backstop cover to banks/MFIs for micro loans",
    "description": "Guarantees payment defaults on micro loans given by registered banks and MFIs to micro units.",
    "financial_assistance_details": "Covers Mudra loans (up to ₹20L) and PM SVANidhi loans, incentivizing banks to lend without collateral.",
    "documents_required": ["Aadhaar", "PAN", "Standard Mudra/SVANidhi Loan Form", "Business KYC"],
    "application_process": "Applied automatically by lending institutions during Mudra/SVANidhi sanction.",
    "nature_of_loan": "Credit Guarantee Facility",
    "interest_rate": "Standard Mudra bank rate",
    "official_website_link": "https://www.ncgtc.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://www.ncgtc.in"
  },
  {
    "id": 20,
    "scheme_name": "Deendayal Antyodaya Yojana - National Rural Livelihoods Mission (DAY-NRLM)",
    "ministry_or_department": "Ministry of Rural Development",
    "eligibility_category": "Rural Poor Households, Women Self-Help Groups (SHGs)",
    "min_age": 18,
    "max_age": 60,
    "max_income": "Identified through SECC survey / Community process",
    "business_sector": "Agriculture, Animal Husbandry, Handicrafts, Rural Retail",
    "target_group": "Rural poor women organized into SHGs and Producer Groups",
    "main_benefit": "Revolving Fund (RF), Community Investment Fund (CIF), and 7% Interest Subvention",
    "min_loan": "₹20,000 (Revolving Fund)",
    "max_loan": "₹20,00,000 (Collateral-free loan to SHGs)",
    "subsidy": "Interest subvention bringing loan interest rate down to 7% (4% on prompt repayment)",
    "description": "Poverty alleviation program organizing rural women into SHGs and providing revolving capital and bank credit linkages.",
    "financial_assistance_details": "Revolving Fund of ₹20,000–₹30,000/SHG; CIF up to ₹1.5 Lakh/SHG; Collateral-free bank loans up to ₹20 Lakh.",
    "documents_required": ["SHG Resolution Form", "Members' Aadhaar Cards", "SHG Bank Passbook", "Gram Panchayat Endorsement"],
    "application_process": "Apply through local Block Development Office (BDO) / District Mission Management Unit (DMMU).",
    "nature_of_loan": "Group Term Loan / Revolving Credit Line",
    "interest_rate": "7% p.a. (effective 4% with prompt repayment bonus)",
    "official_website_link": "https://nrlm.gov.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://nrlm.gov.in"
  },
  {
    "id": 21,
    "scheme_name": "Deendayal Antyodaya Yojana - National Urban Livelihoods Mission (DAY-NULM)",
    "ministry_or_department": "Ministry of Housing and Urban Affairs",
    "eligibility_category": "Urban Poor, Urban SHGs, Individual Urban Entrepreneurs",
    "min_age": 18,
    "max_age": 60,
    "max_income": "Urban poor household identification",
    "business_sector": "Urban Micro-enterprises, Service Trade, Artisanal Units",
    "target_group": "Urban poor individuals and self-help groups",
    "main_benefit": "Interest subvention on bank credit for micro-enterprise setup",
    "min_loan": "₹50,000",
    "max_loan": "₹2,00,000 (Individual) / ₹10,00,000 (Group)",
    "subsidy": "Interest subvention over 7% p.a. paid directly by government",
    "description": "Reduces poverty of urban poor households by enabling access to self-employment and skilled wage employment.",
    "financial_assistance_details": "Subsidized bank loans for micro-units; extra 3% interest subvention for women entrepreneurs.",
    "documents_required": ["Aadhaar Card", "Urban Poor ID / Ration Card", "Project Costing Sheet", "Bank Passbook"],
    "application_process": "Apply via DAY-NULM web portal or through Urban Local Body (ULB) office.",
    "nature_of_loan": "Subsidized Term Loan",
    "interest_rate": "Effective 7% p.a.",
    "official_website_link": "https://nulm.gov.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://nulm.gov.in"
  },
  {
    "id": 22,
    "scheme_name": "PM Formalisation of Micro Food Processing Enterprises (PMFME)",
    "ministry_or_department": "Ministry of Food Processing Industries",
    "eligibility_category": "Individual Micro Food Processing Units, SHGs, FPOs, Cooperatives",
    "min_age": 18,
    "max_age": "No Upper Limit",
    "max_income": "No Income Ceiling",
    "business_sector": "Food Processing (ODOP products, pickles, bakery, spices, oil extraction)",
    "target_group": "Unorganized micro food processing enterprises",
    "main_benefit": "Credit-linked capital subsidy up to 35% + seed capital for SHG members",
    "min_loan": "₹1,00,000",
    "max_loan": "₹10,00,000 (Subsidy cap)",
    "subsidy": "35% credit-linked capital subsidy (Max ₹10 Lakh per unit) + ₹40,000 seed capital per SHG member",
    "description": "Supports formalization, technical upgrade, branding, and marketing for unorganized micro food business operators.",
    "financial_assistance_details": "35% capital subsidy on eligible project cost; ₹40,000 seed capital per SHG member for working capital.",
    "documents_required": ["Aadhaar & PAN", "Udyam Registration", "FSSAI License / Application", "Bank Statements", "Project DPR"],
    "application_process": "Apply online via the official PMFME portal.",
    "nature_of_loan": "Credit-Linked Term Loan",
    "interest_rate": "Standard bank lending interest rate",
    "official_website_link": "https://pmfme.mofpi.gov.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://pmfme.mofpi.gov.in"
  },
  {
    "id": 23,
    "scheme_name": "Agriculture Infrastructure Fund (AIF)",
    "ministry_or_department": "Department of Agriculture and Farmers Welfare",
    "eligibility_category": "Agri-Entrepreneurs, Startups, Farmers, FPOs, PACS, SHGs",
    "min_age": 18,
    "max_age": "No Upper Limit",
    "max_income": "No Ceiling",
    "business_sector": "Post-Harvest Management, Warehousing, Cold Chains, Agri-logistics",
    "target_group": "Agricultural infrastructure developers and agri-startups",
    "main_benefit": "3% Interest Subvention p.a. + CGTMSE credit guarantee cover",
    "min_loan": "₹10,00,000",
    "max_loan": "₹2,00,00,000 (per project)",
    "subsidy": "3% interest subvention for 7 years + free credit guarantee fee coverage",
    "description": "Medium-to-long term debt financing facility for investment in viable post-harvest management infrastructure projects.",
    "financial_assistance_details": "Loans up to ₹2 Crore carry 3% interest subvention for up to 7 years. CGTMSE fee covered by government.",
    "documents_required": ["Land Documents / Lease", "DPR / Feasibility Report", "Firm Registration / GST", "Aadhaar & PAN"],
    "application_process": "Apply online through the AIF portal.",
    "nature_of_loan": "Term Loan",
    "interest_rate": "Capped at 9% p.a. by banks (effective 6% after subvention)",
    "official_website_link": "https://agriinfra.dac.gov.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://agriinfra.dac.gov.in"
  },
  {
    "id": 24,
    "scheme_name": "Production Linked Incentive (PLI) Scheme for Food Processing Industry",
    "ministry_or_department": "Ministry of Food Processing Industries",
    "eligibility_category": "Registered Food Processing Enterprises & Manufacturers",
    "min_age": "N/A (Entity Level)",
    "max_age": "N/A",
    "max_income": "Minimum investment and turnover threshold requirements apply",
    "business_sector": "Ready to Eat/Cook Food, Processed Fruits/Vegetables, Marine Products, Mozzarella Cheese",
    "target_group": "Medium & Large Scale Food Manufacturing Enterprises",
    "main_benefit": "Direct cash incentive on incremental sales and global branding support",
    "min_loan": "N/A (Incentive Scheme)",
    "max_loan": "N/A",
    "subsidy": "4% to 10% incentive on incremental sales for 6 years",
    "description": "Supports creation of global food manufacturing champions and promotes Indian food product brands abroad.",
    "financial_assistance_details": "Direct financial incentive calculated as a percentage of incremental annual sales.",
    "documents_required": ["GST Returns", "Audited Financial Statements", "Manufacturing License", "Export Documents"],
    "application_process": "Apply through the PLI-FPI online portal during call for proposals.",
    "nature_of_loan": "Direct Production-Linked Cash Incentive",
    "interest_rate": "0%",
    "official_website_link": "https://pli-fpi.mofpi.gov.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://pli-fpi.mofpi.gov.in"
  },
  {
    "id": 25,
    "scheme_name": "National Livestock Mission (NLM) - Entrepreneurship Scheme",
    "ministry_or_department": "Department of Animal Husbandry and Dairying",
    "eligibility_category": "Individuals, FPOs, JLGs, SHGs, Section 8 Companies",
    "min_age": 18,
    "max_age": "No Upper Limit",
    "max_income": "No Ceiling",
    "business_sector": "Poultry, Sheep, Goat, Piggery Breeding, Fodder Enterprise",
    "target_group": "Livestock sector entrepreneurs and breeders",
    "main_benefit": "50% capital subsidy for establishing livestock breeding farms and fodder processing units",
    "min_loan": "₹10,00,000",
    "max_loan": "₹50,00,000 (Subsidy cap)",
    "subsidy": "50% capital subsidy up to ₹50 Lakh depending on activity",
    "description": "Drives entrepreneurship development and breed improvement in poultry, sheep, goat, and piggery sectors.",
    "financial_assistance_details": "50% direct capital subsidy released in 2 equal tranches into beneficiary's loan account.",
    "documents_required": ["Land Documents", "Project Feasibility Report", "Training Certificate in Livestock", "Aadhaar & PAN", "Bank Sanction Letter"],
    "application_process": "Apply online via the NLM Udyami Mitra portal.",
    "nature_of_loan": "Credit-Linked Capital Subsidy",
    "interest_rate": "Standard bank loan interest rate",
    "official_website_link": "https://nlm.udyamimitra.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://nlm.udyamimitra.in"
  },
  {
    "id": 26,
    "scheme_name": "Weaver Mudra Scheme / Handloom Concessional Credit",
    "ministry_or_department": "Ministry of Textiles",
    "eligibility_category": "Handloom Weavers and Weaver Entrepreneurs",
    "min_age": 18,
    "max_age": 65,
    "max_income": "No Income Bar",
    "business_sector": "Handloom Weaving and Textile Craft",
    "target_group": "Handloom weavers and craft workers",
    "main_benefit": "Concessional working capital/term loan with margin money assistance and 7% interest subvention",
    "min_loan": "₹10,00,000",
    "max_loan": "₹2,00,000 (Individual) / ₹10,00,000 (Handloom Enterprise)",
    "subsidy": "Margin money subsidy up to 20% of project cost (max ₹25,000) + 6% - 7% interest subvention for 3 years",
    "description": "Provides credit assistance to handloom weavers for purchasing yarn, equipment, and working capital.",
    "financial_assistance_details": "Loans provided at subsidized 6% interest rate; margin money assistance up to ₹25,000 per weaver.",
    "documents_required": ["Weaver ID / Pehchan Card", "Aadhaar Card", "Bank Account Details", "Quotation for Raw Material"],
    "application_process": "Apply via Weaver Mudra Portal or through Weavers' Service Centres (WSCs).",
    "nature_of_loan": "Term Loan / Working Capital Credit Line",
    "interest_rate": "Effective 6% p.a. to beneficiary",
    "official_website_link": "https://handlooms.nic.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://handlooms.nic.in"
  },
  {
    "id": 27,
    "scheme_name": "ASPIRE (Scheme for Promotion of Innovation, Rural Industry & Entrepreneurship)",
    "ministry_or_department": "Ministry of Micro, Small and Medium Enterprises",
    "eligibility_category": "Technical Institutes, Universities, Government Agencies, Industry Associations, Incubators",
    "min_age": "N/A (Institutional level for setup; 18+ for trainees)",
    "max_age": "N/A",
    "max_income": "No Ceiling",
    "business_sector": "Agri-Rural Enterprises, Agro-Processing, Livelihood Business Incubation",
    "target_group": "Rural entrepreneurs and livelihood incubation centers",
    "main_benefit": "100% grant for establishing Livelihood Business Incubators (LBIs)",
    "min_loan": "N/A (Capital Grant)",
    "max_loan": "Up to ₹1 Crore grant per center",
    "subsidy": "100% financial grant up to ₹1 Crore for plant and machinery",
    "description": "Sets up network of technology and livelihood incubators to create rural enterprise employment.",
    "financial_assistance_details": "One-time 100% grant up to ₹1 Crore for machinery to setup Livelihood Incubators.",
    "documents_required": ["Institute Registration", "DPR for Incubator", "Infrastructure Availability Proof", "PAN"],
    "application_process": "Apply online through the ASPIRE Portal hosted by MoMSME.",
    "nature_of_loan": "Institutional Grant / Incubation Support",
    "interest_rate": "0%",
    "official_website_link": "https://aspire.msme.gov.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://aspire.msme.gov.in"
  },
  {
    "id": 28,
    "scheme_name": "SFURTI (Scheme of Fund for Regeneration of Traditional Industries)",
    "ministry_or_department": "Ministry of Micro, Small and Medium Enterprises / KVIC / Coir Board",
    "eligibility_category": "Artisan Clusters, NGOs, Field Institutions, State Govt Agencies, SPVs",
    "min_age": 18,
    "max_age": "No Upper Limit",
    "max_income": "No Ceiling",
    "business_sector": "Khadi, Village Industries, Coir, Bamboo, Honey, Traditional Crafts",
    "target_group": "Traditional artisans organized into cluster SPVs",
    "main_benefit": "Financial grant up to ₹5 Crore for Common Facility Centres (CFCs), modern machinery, and packaging",
    "min_loan": "N/A (Grant Support)",
    "max_loan": "Up to ₹2.5 Crore (Regular Clusters) / ₹5 Crore (Major Clusters)",
    "subsidy": "up to 90% grant funding for cluster infrastructure and machinery",
    "description": "Organizes traditional artisans into clusters to make them competitive and commercially sustainable.",
    "financial_assistance_details": "Financial assistance up to ₹5 Crore for setting up CFCs, training, design intervention, and marketing.",
    "documents_required": ["Cluster Diagnostic Study Report", "DPR", "NGO/Agency Registration", "Land for CFC"],
    "application_process": "Submit proposal via SFURTI online portal to Nodal Agencies (KVIC/Coir Board/NIMSME).",
    "nature_of_loan": "Cluster Development Grant",
    "interest_rate": "0%",
    "official_website_link": "https://sfurti.msme.gov.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://sfurti.msme.gov.in"
  },
  {
    "id": 29,
    "scheme_name": "Procurement and Marketing Support (PMS) Scheme",
    "ministry_or_department": "Ministry of Micro, Small and Medium Enterprises",
    "eligibility_category": "Micro and Small Enterprises (MSEs) with valid Udyam Registration",
    "min_age": 18,
    "max_age": "No Upper Limit",
    "max_income": "MSE Turnover Limits",
    "business_sector": "Manufacturing and Service MSEs",
    "target_group": "Micro and Small enterprise owners seeking market expansion",
    "main_benefit": "100% space rent subsidy for trade fairs, exhibition participation reimbursement, and e-commerce onboard support",
    "min_loan": "N/A (Reimbursement Grant)",
    "max_loan": "Up to ₹1.5 Lakh per exhibition stall",
    "subsidy": "100% stall charge subsidy for SC/ST/Women/NER MSEs; 80% for General MSEs",
    "description": "Promotes marketing capability and export market access for micro and small units.",
    "financial_assistance_details": "Full or partial reimbursement for stall rent, airfare, and trade fair participation fees.",
    "documents_required": ["Udyam Registration Certificate", "Fair Participation Proof", "GST Invoice & Payment Receipt", "Aadhaar & PAN"],
    "application_process": "Apply online on the PMS portal of MoMSME.",
    "nature_of_loan": "Marketing Support Grant / Subsidy",
    "interest_rate": "0%",
    "official_website_link": "https://pms.msme.gov.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://pms.msme.gov.in"
  },
  {
    "id": 30,
    "scheme_name": "Entrepreneurship Skill Development Programme (ESDP)",
    "ministry_or_department": "Ministry of Micro, Small and Medium Enterprises",
    "eligibility_category": "Youth and aspiring entrepreneurs",
    "min_age": 18,
    "max_age": 45,
    "max_income": "No Income Bar",
    "business_sector": "Cross-sectoral (Electronics, Agro, Food, Garmenting, Mechanical, Services)",
    "target_group": "Unemployed youth, students, and potential entrepreneurs",
    "main_benefit": "Free technical skill and business management training modules",
    "min_loan": "N/A (Training Scheme)",
    "max_loan": "N/A (Provides loan assistance guidance under PMEGP/Mudra post-training)",
    "subsidy": "100% course fee waiver",
    "description": "Builds entrepreneurial capabilities and technical expertise to motivate creation of new micro-enterprises.",
    "financial_assistance_details": "Free training, technical workshops, enterprise setup mentoring, and handholding for bank credit.",
    "documents_required": ["Aadhaar Card", "Educational Qualification Certificate", "Passport Photo"],
    "application_process": "Apply through nearest MSME-Development & Facilitation Office (MSME-DFO) or MSME portal.",
    "nature_of_loan": "Non-loan Skill Training",
    "interest_rate": "0%",
    "official_website_link": "https://msme.gov.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://msme.gov.in"
  },
  {
    "id": 31,
    "scheme_name": "NAMASTE / Self Employment Scheme for Rehabilitation of Sanitation Workers",
    "ministry_or_department": "Ministry of Social Justice and Empowerment / NSKFDC",
    "eligibility_category": "Sanitation Workers, Sewer Cleaners, and their Dependents",
    "min_age": 18,
    "max_age": 60,
    "max_income": "No Income Bar",
    "business_sector": "Mechanized Sanitation Services, Commercial Vehicles, Alternative Livelihoods",
    "target_group": "Sanitation workers and sewer maintenance personnel",
    "main_benefit": "Capital subsidy up to 50% for purchasing sanitation vehicles/machinery + concessional loan",
    "min_loan": "₹10,00,000",
    "max_loan": "₹15,00,000",
    "subsidy": "Capital subsidy up to 50% (Max ₹5 Lakh) + 4% - 6% interest rate loan",
    "description": "Eliminates unsafe manual sewer cleaning by financing worker-owned mechanized sanitation equipment.",
    "financial_assistance_details": "50% upfront capital subsidy + low-interest loan for buying suction vehicles, jetting machines, and safety equipment.",
    "documents_required": ["Sanitation Worker Identification / Profiling Card", "Aadhaar Card", "Bank Account Details", "Vehicle Quotation"],
    "application_process": "Apply via NSKFDC portal or Urban Local Body (ULB) sanitation department.",
    "nature_of_loan": "Subsidized Equipment Loan",
    "interest_rate": "4% to 6% p.a.",
    "official_website_link": "https://nskfdc.nic.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://nskfdc.nic.in"
  },
  {
    "id": 32,
    "scheme_name": "Mahila Coir Yojana",
    "ministry_or_department": "Ministry of Micro, Small and Medium Enterprises / Coir Board",
    "eligibility_category": "Rural Women Artisans in Coir-producing Regions",
    "min_age": 18,
    "max_age": 55,
    "max_income": "No Income Bar",
    "business_sector": "Coir Industry (Coir yarn spinning, mats, handicrafts)",
    "target_group": "Rural women coir workers",
    "main_benefit": "75% subsidy on motorized coir spinning ratts/machinery + skill training stipend",
    "min_loan": "N/A",
    "max_loan": "Equipment subsidy purchase",
    "subsidy": "75% cost subsidy on coir machinery + training stipend",
    "description": "Empowers rural women by providing skill training and subsidized coir processing machinery.",
    "financial_assistance_details": "Women receive 2-month training with stipend and 75% equipment purchase subsidy.",
    "documents_required": ["Aadhaar Card", "Bank Account Details", "Address Proof", "Passport Photograph"],
    "application_process": "Apply through regional Coir Board offices or Coir Cooperatives.",
    "nature_of_loan": "Equipment Subsidy Grant",
    "interest_rate": "0%",
    "official_website_link": "http://coirboard.gov.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "http://coirboard.gov.in"
  },
  {
    "id": 33,
    "scheme_name": "National Beekeeping & Honey Mission (NBHM)",
    "ministry_or_department": "Department of Agriculture and Farmers Welfare / NBB",
    "eligibility_category": "Beekeepers, Farmers, SHGs, FPOs, Agri-entrepreneurs",
    "min_age": 18,
    "max_age": "No Upper Limit",
    "max_income": "No Ceiling",
    "business_sector": "Apiculture, Honey Production, Beehive Equipment, Honey Testing Labs",
    "target_group": "Beekeepers and apiculture entrepreneurs",
    "main_benefit": "Subsidy up to 80% for beehives, colonies, honey extraction equipment, and custom hiring centers",
    "min_loan": "₹50,000",
    "max_loan": "Up to ₹5 Crore (for commercial processing/testing infrastructure)",
    "subsidy": "40% to 80% subsidy depending on component (hives/processing/labs)",
    "description": "Promotes 'Sweet Revolution' through holistic development of scientific apiculture and honey production.",
    "financial_assistance_details": "40%-80% subsidy for beehive sets; 50% subsidy for honey processing plants.",
    "documents_required": ["Aadhaar Card", "NBB Registration Certificate", "Land Documents", "Bank Account Passbook"],
    "application_process": "Apply online through Madhukrantis portal / National Bee Board website.",
    "nature_of_loan": "Credit-Linked Capital Subsidy",
    "interest_rate": "As per standard bank rates",
    "official_website_link": "https://nbhm.gov.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://nbhm.gov.in"
  },
  {
    "id": 34,
    "scheme_name": "Single Point Registration Scheme (SPRS) - NSIC",
    "ministry_or_department": "Ministry of Micro, Small and Medium Enterprises / NSIC",
    "eligibility_category": "Micro and Small Enterprises (MSEs) holding Udyam Registration",
    "min_age": 18,
    "max_age": "No Upper Limit",
    "max_income": "MSE Turnover Limits",
    "business_sector": "Manufacturing and Commercial Service Providers",
    "target_group": "MSEs participating in Government Procurement (DGS&D / PSUs)",
    "main_benefit": "Exemption from Earnest Money Deposit (EMD), free tender sets, and 15% price preference",
    "min_loan": "N/A (Procurement Incentive Scheme)",
    "max_loan": "N/A",
    "subsidy": "100% waiver of EMD and tender document costs in government tenders",
    "description": "Assists MSEs in securing Government Purchase Contracts by removing tender financial barriers.",
    "financial_assistance_details": "Free tender forms, EMD exemption, and L1+15% price preference in public tenders.",
    "documents_required": ["Udyam Certificate", "Plant Machinery Ownership Proof", "3 Years Audited Financials", "PAN & GSTIN"],
    "application_process": "Apply online on NSIC SPRS portal.",
    "nature_of_loan": "Procurement Facilitation / Fee Exemption",
    "interest_rate": "0%",
    "official_website_link": "https://www.sprs.nsic.co.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://www.sprs.nsic.co.in"
  },
  {
    "id": 35,
    "scheme_name": "Raw Material Assistance (RMA) Scheme - NSIC",
    "ministry_or_department": "Ministry of Micro, Small and Medium Enterprises / NSIC",
    "eligibility_category": "Manufacturing Micro and Small Enterprises (MSEs)",
    "min_age": 18,
    "max_age": "No Upper Limit",
    "max_income": "MSE Ceiling",
    "business_sector": "Industrial Manufacturing and Fabrication",
    "target_group": "Manufacturing MSE units",
    "main_benefit": "Financial credit assistance to procure raw materials against Bank Guarantee",
    "min_loan": "₹5,00,000",
    "max_loan": "Based on Bank Guarantee value (up to multi-crores)",
    "subsidy": "Bulk discount benefits passed directly to MSEs; lower interest credit short-term facility",
    "description": "Finances procurement of industrial raw materials (indigenous & imported) to ensure uninterrupted production.",
    "financial_assistance_details": "Credit limit provided against Bank Guarantee for up to 180 days at nominal interest rates.",
    "documents_required": ["Bank Guarantee from Approved Bank", "Udyam Certificate", "Raw Material Requisition Form", "KYC Docs"],
    "application_process": "Apply at nearest NSIC Branch Office or online via NSIC portal.",
    "nature_of_loan": "Short-term Credit Line for Raw Material Procurement",
    "interest_rate": "8% to 10.5% p.a. (short-term)",
    "official_website_link": "https://www.nsic.co.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://www.nsic.co.in"
  },
  {
    "id": 36,
    "scheme_name": "Micro & Small Enterprises Cluster Development Programme (MSE-CDP)",
    "ministry_or_department": "Ministry of Micro, Small and Medium Enterprises",
    "eligibility_category": "Cluster Associations, Groups of minimum 20 MSEs, State Agencies",
    "min_age": "N/A (Group Entity)",
    "max_age": "N/A",
    "max_income": "No Ceiling",
    "business_sector": "Industrial Sector Clusters (Textiles, Leather, Metalwork, Agro)",
    "target_group": "MSE Clusters seeking shared industrial infrastructure",
    "main_benefit": "Financial grant up to ₹30 Crore for setting up Common Facility Centres (CFCs)",
    "min_loan": "N/A (Infrastructure Grant)",
    "max_loan": "Up to ₹30 Crore (CFC) / ₹15 Crore (Infrastructure Upgrade)",
    "subsidy": "60% to 80% grant support of project cost",
    "description": "Enhances competitiveness of MSEs through common testing labs, design centers, effluent treatment, and infrastructure.",
    "financial_assistance_details": "70%–80% financial grant for CFCs in special areas/category clusters; 60% for standard clusters.",
    "documents_required": ["Detailed Project Report (DPR)", "SPV Registration Proof", "Land Commitment Letter", "Cluster Survey"],
    "application_process": "Submit proposal through State Industry Department to MoMSME Cluster Portal.",
    "nature_of_loan": "Capital Grant for Cluster SPVs",
    "interest_rate": "0%",
    "official_website_link": "https://cluster.msme.gov.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://cluster.msme.gov.in"
  },
  {
    "id": 37,
    "scheme_name": "Modified Credit Linked Capital Subsidy Scheme (CLCSS)",
    "ministry_or_department": "Ministry of Micro, Small and Medium Enterprises",
    "eligibility_category": "Sole Proprietorships, Partnerships, Private Limited MSEs upgrading plant technology",
    "min_age": 18,
    "max_age": "No Upper Limit",
    "max_income": "MSE Ceiling",
    "business_sector": "51 Approved Manufacturing & Processing Sub-Sectors",
    "target_group": "MSEs adopting advanced technological machinery",
    "main_benefit": "15% upfront capital subsidy on institutional finance for technology purchase",
    "min_loan": "₹10,00,000",
    "max_loan": "₹1,00,00,000 (Loan eligible for subsidy)",
    "subsidy": "15% capital subsidy upfront (Max ₹15 Lakh)",
    "description": "Facilitates technology modernization of micro and small enterprises by subsidizing plant machinery upgrades.",
    "financial_assistance_details": "15% capital subsidy credited directly to loan account for machinery purchase up to ₹1 Crore.",
    "documents_required": ["Udyam Certificate", "Machinery Invoices & Quotation", "Bank Loan Sanction Letter", "Audited Accounts"],
    "application_process": "Apply through lending Nodal Bank / SIDBI online CLCSS portal.",
    "nature_of_loan": "Credit-Linked Upfront Capital Subsidy",
    "interest_rate": "Standard term loan interest rate",
    "official_website_link": "https://dashboard.msme.gov.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://dashboard.msme.gov.in"
  },
  {
    "id": 38,
    "scheme_name": "Special Credit Linked Capital Subsidy Scheme (SCLCSS) for SC/ST",
    "ministry_or_department": "Ministry of Micro, Small and Medium Enterprises / NSSH",
    "eligibility_category": "SC and ST Owned Micro and Small Enterprises",
    "min_age": 18,
    "max_age": "No Upper Limit",
    "max_income": "MSE Ceiling",
    "business_sector": "Manufacturing and Service Sector MSEs",
    "target_group": "SC/ST entrepreneurs modernizing business operations",
    "main_benefit": "25% upfront capital subsidy on institutional credit without sector restriction",
    "min_loan": "₹5,00,000",
    "max_loan": "₹1,00,00,000 (Loan eligible for subsidy)",
    "subsidy": "25% capital subsidy upfront (Max ₹25 Lakh)",
    "description": "Higher capital subsidy rate specifically for SC/ST enterprises to upgrade plant and equipment.",
    "financial_assistance_details": "25% capital subsidy directly credited to loan account on institutional term loan up to ₹1 Crore.",
    "documents_required": ["Caste Certificate (SC/ST)", "Udyam Certificate", "Bank Sanction Letter", "Machinery Invoices"],
    "application_process": "Apply via lending bank through National SC-ST Hub / Nodal Agency portal.",
    "nature_of_loan": "Credit-Linked Capital Subsidy",
    "interest_rate": "As charged by lending institution",
    "official_website_link": "https://www.scsthub.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://www.scsthub.in"
  },
  {
    "id": 39,
    "scheme_name": "National SC-ST Hub (NSSH) Capacity Building & Market Access Scheme",
    "ministry_or_department": "Ministry of Micro, Small and Medium Enterprises",
    "eligibility_category": "SC and ST Owned MSE Enterprises",
    "min_age": 18,
    "max_age": "No Upper Limit",
    "max_income": "MSE Ceiling",
    "business_sector": "All Manufacturing and Commercial Service Trade",
    "target_group": "SC/ST entrepreneurs",
    "main_benefit": "80% to 100% reimbursement of fee charges for certifications, exhibitions, testing, and software tools",
    "min_loan": "N/A (Reimbursement Grant)",
    "max_loan": "Up to ₹1 Lakh per component reimbursement",
    "subsidy": "80% - 100% reimbursement of testing fees, ISO registration, and trade show costs",
    "description": "Builds operational capacity of SC/ST enterprises to fulfill the 4% mandatory government procurement mandate.",
    "financial_assistance_details": "Reimbursement of 80% cost of testing charges, ISO certification, GeM portal fees, and trade fair stalls.",
    "documents_required": ["SC/ST Certificate", "Udyam Certificate", "Payment Receipts / Tax Invoices", "Bank Details"],
    "application_process": "Apply on the official National SC-ST Hub portal.",
    "nature_of_loan": "Capacity Building Grant Reimbursement",
    "interest_rate": "0%",
    "official_website_link": "https://www.scsthub.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://www.scsthub.in"
  },
  {
    "id": 40,
    "scheme_name": "Gramodyog Vikas Yojana (GVY)",
    "ministry_or_department": "Ministry of Micro, Small and Medium Enterprises / KVIC",
    "eligibility_category": "Rural Artisans, Potter Families, Agarbatti Artisans, Village Craftspersons",
    "min_age": 18,
    "max_age": 55,
    "max_income": "Rural artisan family status",
    "business_sector": "Village Industries (Pottery, Honey, Agarbatti, Leather, Handcrafted paper)",
    "target_group": "Rural traditional artisans",
    "main_benefit": "100% free distribution of electric potter wheels, modern toolkits, and skill training",
    "min_loan": "N/A (Machinery Grant)",
    "max_loan": "N/A",
    "subsidy": "100% equipment grant distribution + daily training stipend",
    "description": "Promotes village industry activity by modernizing traditional artisan toolsets and manufacturing technology.",
    "financial_assistance_details": "Provides motorized pottery wheels, agarbatti making machines, beehive boxes, and technical skill upgrades.",
    "documents_required": ["Aadhaar Card", "Artisan Proof / Panchayat Certificate", "Bank Passbook"],
    "application_process": "Apply via KVIC Gramodyog portal or field offices.",
    "nature_of_loan": "In-kind Equipment Grant",
    "interest_rate": "0%",
    "official_website_link": "https://www.kviconline.gov.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://www.kviconline.gov.in"
  },
  {
    "id": 41,
    "scheme_name": "Adivasi Mahila Swashaktikaran Yojana (AMSY)",
    "ministry_or_department": "Ministry of Tribal Affairs / NSTFDC",
    "eligibility_category": "Scheduled Tribe (ST) Women Entrepreneurs and SHG Members",
    "min_age": 18,
    "max_age": 60,
    "max_income": "Double the Poverty Line (DPL) limits for STs",
    "business_sector": "Minor Forest Produce processing, Agriculture, Petty Shopkeeping, Weaving",
    "target_group": "ST women entrepreneurs",
    "main_benefit": "Highly concessional term loan up to ₹2,00,000 at 4% p.a. interest",
    "min_loan": "₹10,000",
    "max_loan": "₹2,00,000",
    "subsidy": "Up to 90% project cost covered by concessional credit line",
    "description": "Exclusively designed for economic development and self-employment of tribal women.",
    "financial_assistance_details": "Loans up to ₹2 Lakh per beneficiary at 4% p.a. interest rate. Tenure up to 10 years.",
    "documents_required": ["ST Caste Certificate", "Aadhaar Card", "Income Certificate", "Bank Account Details"],
    "application_process": "Apply through State Channelizing Agencies (SCAs) of NSTFDC.",
    "nature_of_loan": "Concessional Term Loan",
    "interest_rate": "4% p.a.",
    "official_website_link": "https://nstfdc.tribal.gov.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://nstfdc.tribal.gov.in"
  },
  {
    "id": 42,
    "scheme_name": "Term Loan Scheme - NSTFDC",
    "ministry_or_department": "Ministry of Tribal Affairs / NSTFDC",
    "eligibility_category": "Scheduled Tribe (ST) Individuals or Business Entities (>51% ST owned)",
    "min_age": 18,
    "max_age": 65,
    "max_income": "Double Poverty Line (DPL) limits",
    "business_sector": "Agriculture, Transport Vehicles, Trading, Small Industry, Services",
    "target_group": "Tribal entrepreneurs and enterprise owners",
    "main_benefit": "Term loan up to ₹10 Lakh per unit at subsidized 6% to 8% interest rate",
    "min_loan": "₹50,000",
    "max_loan": "₹10,00,000",
    "subsidy": "Up to 90% project financing cover",
    "description": "Finances viable commercial units for tribal individuals to boost income generation.",
    "financial_assistance_details": "Loans up to ₹10 Lakh with interest rates of 6% (up to ₹5L) and 8% (above ₹5L). Repayment up to 10 years.",
    "documents_required": ["ST Caste Certificate", "Aadhaar Card", "Project Feasibility Report", "Bank Passbook"],
    "application_process": "Apply via State Channelizing Agencies / NSTFDC portal.",
    "nature_of_loan": "Term Loan",
    "interest_rate": "6% to 8% p.a.",
    "official_website_link": "https://nstfdc.tribal.gov.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://nstfdc.tribal.gov.in"
  },
  {
    "id": 43,
    "scheme_name": "Micro Credit Scheme for Self Help Groups - NSTFDC",
    "ministry_or_department": "Ministry of Tribal Affairs / NSTFDC",
    "eligibility_category": "ST Members forming Self Help Groups (SHGs)",
    "min_age": 18,
    "max_age": 60,
    "max_income": "Double Poverty Line (DPL) criteria",
    "business_sector": "Micro-activities, Handloom, Forest produce harvesting, Animal Rearing",
    "target_group": "Tribal SHG members",
    "main_benefit": "Quick micro-credit up to ₹50,000 per member and ₹5 Lakh per SHG at 6% interest",
    "min_loan": "₹10,000",
    "max_loan": "₹5,00,000 per SHG (₹50,000 per member)",
    "subsidy": "Low-interest microcredit rate for rural tribal households",
    "description": "Provides micro-credit support for small business needs of tribal SHGs.",
    "financial_assistance_details": "Loans up to ₹50,000 per member at 6% p.a. interest rate for up to 5 years.",
    "documents_required": ["ST Certificate", "SHG Registration & Passbook", "Aadhaar Card of Members"],
    "application_process": "Apply through NSTFDC SCAs or regional tribal development federations.",
    "nature_of_loan": "Microfinance Loan",
    "interest_rate": "6% p.a.",
    "official_website_link": "https://nstfdc.tribal.gov.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://nstfdc.tribal.gov.in"
  },
  {
    "id": 44,
    "scheme_name": "Mahila Samriddhi Yojana - NSKFDC",
    "ministry_or_department": "Ministry of Social Justice and Empowerment / NSKFDC",
    "eligibility_category": "Women Safai Karamcharis, Waste Pickers, and Dependents",
    "min_age": 18,
    "max_age": 50,
    "max_income": "No Income Bar",
    "business_sector": "Petty Trade, Shops, Tailoring, Beauty Parlor, Micro-enterprises",
    "target_group": "Women Safai Karamcharis and waste pickers",
    "main_benefit": "Microcredit term loan up to ₹1,00,000 at 4% p.a. interest",
    "min_loan": "₹10,000",
    "max_loan": "₹1,00,000",
    "subsidy": "90% project cost financed at ultra-low interest rate",
    "description": "Supports socio-economic rehabilitation of women safai karamcharis by creating small enterprise opportunities.",
    "financial_assistance_details": "Loan up to ₹1 Lakh at 4% p.a. interest rate with repayment tenure up to 5 years.",
    "documents_required": ["Safai Karamchari ID/Certificate", "Aadhaar Card", "Bank Account Details"],
    "application_process": "Apply through State Channelizing Agencies (SCAs) or RRBs.",
    "nature_of_loan": "Microcredit Term Loan",
    "interest_rate": "4% p.a.",
    "official_website_link": "https://nskfdc.nic.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://nskfdc.nic.in"
  },
  {
    "id": 45,
    "scheme_name": "General Term Loan Scheme - NSKFDC",
    "ministry_or_department": "Ministry of Social Justice and Empowerment / NSKFDC",
    "eligibility_category": "Safai Karamcharis, Scavengers, and Dependents",
    "min_age": 18,
    "max_age": 60,
    "max_income": "No Income Bar",
    "business_sector": "Commercial Transport, Trading, Small Industry, Service Ventures",
    "target_group": "Safai karamcharis and families",
    "main_benefit": "Term loan up to ₹15 Lakh at concessional interest rate for enterprise creation",
    "min_loan": "₹1,00,000",
    "max_loan": "₹15,00,000",
    "subsidy": "Concessional credit financing up to 90% of project cost",
    "description": "Finances establishment of sustainable self-employment ventures for sanitation workers.",
    "financial_assistance_details": "Loans up to ₹15 Lakh at 6% (up to ₹5L) and 7% (above ₹5L) p.a. interest rate.",
    "documents_required": ["Occupation Certificate (Safai Karamchari)", "Aadhaar Card", "Project Costing Sheet", "Bank Passbook"],
    "application_process": "Apply via NSKFDC State Channelizing Agencies or Jan Samarth portal.",
    "nature_of_loan": "Term Loan",
    "interest_rate": "6% to 7% p.a.",
    "official_website_link": "https://nskfdc.nic.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://www.jansamarth.in"
  },
  {
    "id": 46,
    "scheme_name": "Amended Technology Upgradation Fund Scheme (ATUFS)",
    "ministry_or_department": "Ministry of Textiles",
    "eligibility_category": "Textile, Garment, Technical Textile Manufacturing Units",
    "min_age": "N/A (Firm Entity)",
    "max_age": "N/A",
    "max_income": "No Ceiling",
    "business_sector": "Textile Weaving, Processing, Garmenting, Technical Textiles",
    "target_group": "Textile manufacturing entrepreneurs",
    "main_benefit": "Capital Investment Subsidy (CIS) up to 15% on machinery purchase",
    "min_loan": "₹20,00,000",
    "max_loan": "Up to ₹30 Crore (Subsidy cap)",
    "subsidy": "10% to 15% Capital Investment Subsidy (Max ₹30 Crore depending on sector)",
    "description": "Drives technology benchmark modernization in Indian textile manufacturing.",
    "financial_assistance_details": "10% CIS for Weaving/Processing; 15% CIS for Garmenting & Technical Textiles.",
    "documents_required": ["Udyam Certificate", "Machinery Purchase Invoices", "Bank Sanction Letter", "Joint Inspection Report"],
    "application_process": "Apply online via i-TUFS portal managed by Ministry of Textiles.",
    "nature_of_loan": "Credit-Linked Capital Subsidy",
    "interest_rate": "Standard bank loan interest",
    "official_website_link": "https://atufs.texmin.gov.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://atufs.texmin.gov.in"
  },
  {
    "id": 47,
    "scheme_name": "Startup India Seed Fund Scheme (SISFS)",
    "ministry_or_department": "DPIIT, Ministry of Commerce and Industry",
    "eligibility_category": "DPIIT-Recognized Startups (Incorporated within last 2 years)",
    "min_age": 18,
    "max_age": "No Upper Limit",
    "max_income": "No Ceiling",
    "business_sector": "Technology, Hardware, Healthcare, FinTech, AgriTech, CleanTech, DeepTech",
    "target_group": "Early-stage innovative startups",
    "main_benefit": "Financial grant up to ₹20 Lakh for prototype + debt up to ₹50 Lakh for commercialization",
    "min_loan": "₹10,00,000",
    "max_loan": "₹70,00,000 (Grant + Debt combined cap)",
    "subsidy": "Grant funding for proof-of-concept and prototype development",
    "description": "Provides seed capital to early-stage startups through selected incubators across India.",
    "financial_assistance_details": "Grants up to ₹20 Lakh for proof-of-concept/prototype; convertible debentures/debt up to ₹50 Lakh for commercial launch.",
    "documents_required": ["DPIIT Recognition Certificate", "Incorporation Certificate", "Pitch Deck", "Bank Details"],
    "application_process": "Apply online via the Seed Fund Portal of Startup India.",
    "nature_of_loan": "Seed Grant / Convertible Debt",
    "interest_rate": "Subsidized / Nominal rate on debt portion (up to 8% p.a.)",
    "official_website_link": "https://seedfund.startupindia.gov.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://seedfund.startupindia.gov.in"
  },
  {
    "id": 48,
    "scheme_name": "Credit Guarantee Scheme for Startups (CGSS)",
    "ministry_or_department": "DPIIT, Ministry of Commerce and Industry / NCGTC",
    "eligibility_category": "DPIIT-Recognized Startups seeking venture debt/debt financing",
    "min_age": 18,
    "max_age": "No Upper Limit",
    "max_income": "No Ceiling",
    "business_sector": "All Innovative Startup Sectors",
    "target_group": "Growth-stage DPIIT startups requiring collateral-free venture loans",
    "main_benefit": "Credit guarantee cover up to ₹10 Crore on bank loans provided to startups",
    "min_loan": "₹50,00,000",
    "max_loan": "₹10,00,00,000",
    "subsidy": "Government guarantee cover up to 80% of default risk",
    "description": "Encourages banks and AIFs to extend collateral-free venture debt financing to startups.",
    "financial_assistance_details": "Guarantee cover provided to member banks for loans up to ₹10 Crore per startup.",
    "documents_required": ["DPIIT Certificate", "Startup Balance Sheet", "Venture Debt Terms", "Aadhaar & PAN"],
    "application_process": "Applied by participating scheduled commercial banks/AIFs on behalf of the startup.",
    "nature_of_loan": "Credit Guarantee for Debt/Venture Loans",
    "interest_rate": "As per lending institution norms",
    "official_website_link": "https://www.startupindia.gov.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://www.startupindia.gov.in"
  },
  {
    "id": 49,
    "scheme_name": "Pradhan Mantri Kisan Sampada Yojana (PMKSY) - Integrated Cold Chain",
    "ministry_or_department": "Ministry of Food Processing Industries",
    "eligibility_category": "Agri-Entrepreneurs, FPOs, Cooperatives, Private Companies",
    "min_age": 18,
    "max_age": "No Upper Limit",
    "max_income": "No Ceiling",
    "business_sector": "Cold Chain Storage, Pack Houses, Refrigerated Transport, Value Addition",
    "target_group": "Cold chain infrastructure developers",
    "main_benefit": "Grant-in-aid up to 50% for setting up integrated cold chain facilities",
    "min_loan": "₹1,00,00,000",
    "max_loan": "₹10,00,00,000 (Grant cap)",
    "subsidy": "35% to 50% capital grant-in-aid (Max ₹10 Crore)",
    "description": "Prevents post-harvest agricultural losses by building unbroken cold chain networks from farm-gate to market.",
    "financial_assistance_details": "Grant up to 35% for storage machinery and 50% for value addition/processing equipment.",
    "documents_required": ["Detailed Project Report (DPR)", "Land Ownership/Lease", "Bank Sanction Letter", "Environmental Clearance"],
    "application_process": "Apply through call for proposals on the MoFPI online portal.",
    "nature_of_loan": "Credit-Linked Capital Grant-in-Aid",
    "interest_rate": "Standard bank loan interest",
    "official_website_link": "https://www.mofpi.gov.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://www.mofpi.gov.in"
  },
  {
    "id": 50,
    "scheme_name": "PM Krishi Sinchayee Yojana (PMKSY) - Micro Irrigation / Per Drop More Crop",
    "ministry_or_department": "Department of Agriculture and Farmers Welfare",
    "eligibility_category": "Individual Farmers, Farm Groups, Micro-irrigation Entrepreneurs",
    "min_age": 18,
    "max_age": "No Upper Limit",
    "max_income": "No Ceiling",
    "business_sector": "Agricultural Water Management, Drip & Sprinkler Systems",
    "target_group": "Farmers installing drip/sprinkler micro-irrigation systems",
    "main_benefit": "Subsidy up to 55% for micro-irrigation equipment installation",
    "min_loan": "N/A (Equipment Subsidy)",
    "max_loan": "Up to 5 hectares coverage per farmer",
    "subsidy": "55% for Small/Marginal Farmers; 45% for General Category Farmers",
    "description": "Enhances water use efficiency on farms through pressurized drip and sprinkler micro-irrigation technology.",
    "financial_assistance_details": "Upfront subsidy credited directly to beneficiary/system supplier for drip system installation.",
    "documents_required": ["Land Revenue Document (Khasra/Khatauni)", "Aadhaar Card", "Bank Passbook", "Soil & Water Test Report"],
    "application_process": "Apply via State Agriculture Department micro-irrigation portal.",
    "nature_of_loan": "Equipment Subsidy Grant",
    "interest_rate": "0%",
    "official_website_link": "https://pmksy.gov.in",
    "status": "Active",
    "is_indian_scheme": True,
    "apply_link": "https://pmksy.gov.in"
  }
]

OFFICIAL_LANGUAGES_INDIA = [
    "English", "Hindi (हिन्दी)", "Bengali (বাংলা)", "Telugu (తెలుగు)", "Marathi (मराठी)", 
    "Tamil (தமிழ்)", "Urdu (اردو)", "Gujarati (ગુજરાતી)", "Kannada (ಕನ್ನಡ)", "Malayalam (മലയാളം)", 
    "Odia (ଓଡ଼ିଆ)", "Punjabi (ਪੰਜਾਬੀ)", "Assamese (অসমীয়া)", "Maithili (मैथिली)", "Santali (ᱥᱟᱱᱛᱟᱲᱤ)", 
    "Kashmiri (किसमिरि)", "Nepali (नेपाली)", "Konkani (कोंकणी)", "Dogri (डोगरी)", "Manipuri (ꯃꯩꯇꯩꯂꯣꯟ)", 
    "Bodo (बर')", "Sanskrit (संस्कृतम्)", "Sindhi (सिन्धी)"
]

INDIAN_STATES = [
    "All India",
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal"
]
